### ISSUE TITLE
Are PEP 8 comments supported?

### ISSUE THREAD

**Issue by kiwi0fruit** [DonJayamanne/vscodeJupyter#106]
Does vscodeJupyter support [PEP 8 compatible comments](https://www.python.org/dev/peps/pep-0008/#inline-comments) as cell separators? Like:
```py
# %%
```

**Comment by ogrisel** [comment]
+1 for using the PEP8 compatible comment syntax for the default cell separator in the documentation.

**Comment by kiwi0fruit** [comment]
I've finally tested it. And they actually work.
