### ISSUE TITLE
provide option to disable results window

### ISSUE THREAD

**Issue by shelper** [DonJayamanne/vscodeJupyter#113]
### Environment data
VS Code version:
Jupyter Extension version:
OS and version:

### Logs
Output from ```Jupyter``` output panel
```
```
Output from ```Console window``` (Help->Developer Tools menu)
```
```

### Actual behavior
when run cell, results window automatically opens and shows the results

### Expected  behavior
provide option to disable results window, so that i can have a console running on the side to show the results. some times it is more efficient 

### Steps to reproduce:
-
-

**Comment by DonJayamanne** [comment]
Closing as this disables the entire purpose of the extension

**Comment by shelper** [comment]
i am confused. i think i still want the capability to mark the cell, click to run the cell, and i can have a ipython shell that connects to the kernel to show the results rather than using a results tab in vscode. it does not disable to the entire purpose or maybe i missed something...
