### ISSUE TITLE
Error activating extension, cannot find module

### ISSUE THREAD

**Issue by tblazina** [DonJayamanne/vscodeJupyter#135]
### Environment data
VS Code version: 1.27.2
Jupyter Extension version: 1.1.4
OS and version: Ubuntu 16.04 LTS

### Logs
Output from ```Jupyter``` output panel
```
None
```
Output from ```Console window``` (Help->Developer Tools menu)
```
Activating extension 'donjayamanne.jupyter' failed: Cannot find module '~/.vscode/extensions/donjayamanne.jupyter-1.1.4/out/src/extension'.
```

### Actual behavior

When I try to run any commands, I get popup messages such as:

command 'jupyter.runSelectionLine' not found

### Expected  behavior

That the extension would be found after installing from the vscode marketplace

### Steps to reproduce:
- Install Jupyter from vscode marketplace
- Try to run any python code using the extension

**Comment by DonJayamanne** [comment]
Please reinstall the extension

**Comment by tblazina** [comment]
@DonJayamanne , thanks for the quick reply. I've tried disabling and reinstalling the extension multiple times and the error keeps occurring. I've noticed that when I uninstall the extension the `~/.vscode/extensions/donjayamanne.jupyter-1.1.4` folder still remains. So I've tried to uninstall, manually remove `'~/.vscode/extensions/donjayamanne.jupyter-1.1.4/out/src/extension'` folder and then reinstall. When I do this I, now get the following error:

```
"~/.vscode/extensions/donjayamanne.jupyter-1.1.4/python/PythonTools/ipythonServer.py", line 283, in start_processing     cmd(self, id)   File "~/.vscode/extensions/donjayamanne.jupyter-1.1.4/python/PythonTools/ipythonServer.py", line 354, in _cmd_lstk     kernelspecs = json.dumps(listKernelSpecs())   File "~/.vscode/extensions/donjayamanne.jupyter-1.1.4/python/PythonTools/ipythonServer.py", line 95, in listKernelSpecs     return kernelSpecManager.get_all_specs() AttributeError: 'KernelSpecManager' object has no attribute 'get_all_specs'
```

Any ideas with this one?
