### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/vscodeJupyter#14]
_From @Lucidyan on December 15, 2016 16:38_

## Environment data
VS Code version:  
- Version 1.8.0
- Commit 38746938a4ab94f2f57d9e1309c51fd6fb37553d
- Date 2016-12-13T18:03:00.506Z
- Shell 1.4.6
- Renderer 53.0.2785.143
- Node 6.5.0

Python Extension version:  0.5.5
Python Version:  3.5.2
OS and version:   Ubuntu 16.10 | Linux 4.8.0-30-generic 

## Actual behavior
When I try to format wrong one line like 

> import       pandas as pd

 without new line in the end, with Ctrl+Shift+I, I get

> Cannot read property 'substring' of undefined

But when I add new line to the end of file or write string by pep8, it's working fine.
It's reproduce with yapf, autopep8 crashes without end of file line even with pep8-writed first string.

## Expected  behavior
Autoformatting

_Copied from original issue: DonJayamanne/pythonVSCode#583_

**Comment by DonJayamanne** [comment]
_From @HoweChen on December 19, 2016 9:26_

Same issue here

**Comment by DonJayamanne** [comment]
_From @rjmacarthy on December 21, 2016 10:14_

Same issue here.

**Comment by DonJayamanne** [comment]
_From @tdbear on January 1, 2017 3:57_

+1

**Comment by DonJayamanne** [comment]
_From @lezhiii on January 2, 2017 11:34_

+1

**Comment by DonJayamanne** [comment]
_From @flyfj on January 2, 2017 15:44_

adding new line to the end of the file seems to fix my issue.

**Comment by DonJayamanne** [comment]
_From @tdbear on January 3, 2017 0:7_

Upgrading to 1.9.0 Fixed my issue. Newline at end of file did not fix it. So maybe another issue.

**Comment by DonJayamanne** [comment]
_From @HoweChen on January 9, 2017 14:22_

@tdbear I turned to use insider version and this problem is solved. In fact by using the insider, I have never seen the error in both cases.

**Comment by DonJayamanne** [comment]
_From @BrianDGLS on January 16, 2017 15:56_

Adding an _EMPTY_ new line at the end of the file fixed it for me also.

**Comment by hijkzzz** [comment]
+1
