### ISSUE TITLE
New Jupyter extension cannot run current Python cell code

### ISSUE THREAD

**Issue by nguyen14ck** [DonJayamanne/vscodeJupyter#28]
### Environment data
VS Code version: 1.10.2
Jupyter Extension version: 1.0
OS and version: Windows 10

### Logs
Output from ```Jupyter``` output panel
not start

Output from ```Console window``` (Help->Developer Tools menu)
<div id="site">
<div class="error">
    <h1>404 : Not Found</h1>
<p>You are requesting a page that does not exist!</p>
</header>
</div>

### Actual behavior
Start a new notebook and get html not found
(my home folder of Jupyter is NOT default in My Document folder)

### Expected  behavior
Run cell like version 0.59

### Steps to reproduce:
- Update to Python version 0.60
- Run the current python file with "# %%" cell characters

**Comment by DonJayamanne** [comment]
Once you have tried to start a notebook, could you then try to select from an existing (running) notebook. That should work for now 
FYI, this is a work around.

**Comment by cgranade** [comment]
I also run into this issue. Running Jupyter Notebook in a terminal and viewing its output shows that the Jupyter VS Code extension is requesting a URL of the form ``/%20/api`` (unique IDs removed from output):

```
PS> jupyter notebook
[W 22:22:12.043 NotebookApp] Unrecognized JSON config file version, assuming version 1
[W 22:22:12.045 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 22:22:13.274 NotebookApp] [nb_conda_kernels] enabled, 7 kernels found
[I 22:22:13.785 NotebookApp] [nb_conda] enabled
[I 22:22:13.831 NotebookApp] \u2713 nbpresent HTML export ENABLED
[W 22:22:13.831 NotebookApp] \u2717 nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 22:22:13.894 NotebookApp] [nb_anacondacloud] enabled
[I 22:22:13.967 NotebookApp] Serving notebooks from local directory: C:\Users\Chris
[I 22:22:13.968 NotebookApp] 0 active kernels
[I 22:22:13.968 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 22:22:13.968 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 22:22:19.098 NotebookApp] Kernel started: ...
[W 22:22:31.655 NotebookApp] 404 GET /%20/api/kernelspecs?... (127.0.0.1) 7.51ms referer=None
```

Viewing the same ``/api`` URL in a browser but without the ``/%20`` returns a valid JSON kernelspec, as expected. Please let me know if there's any other diagnostic information I can provide. Thanks!

Component | Version
---|---
VS Code | 1.10.2
Python Extension | 0.6.0
Jupyter Extension | 1.0.0
Python | 3.52 (Anaconda 4.0.0)
Jupyter | 4.1.0

**Comment by DonJayamanne** [comment]
@nguyen14ck , @cgranade 
Once you have tried to start a notebook, could you then try to select from an existing (running) notebook. That should work for now
FYI, this is a work around.

Please let me know if this works.

**Comment by zealseeker** [comment]
@DonJayamanne I got the same problem. No matter I started a notebook by `jupyter notebook` or by vscode, it showed `<!DOCTYPE HTML>` and 404 in console.

**Comment by DonJayamanne** [comment]
Please could you try updating to the latest version of Jupyter and giving it a go.

**Comment by zealseeker** [comment]
@DonJayamanne Unfortunately, I cannot update jupyter neither by `conda update/upgrade`. Maybe bacause it is 32-bits anaconda with python2.7. I will change to 64-bits anaconda and reinstall jupyter in the futher. Then I will test it again and report.

**Comment by zealseeker** [comment]
@DonJayamanne Sorry for the late report. I've reinstalled anaconda and the latest version of this extension works well.

**Comment by DonJayamanne** [comment]
Great, thanks
