### ISSUE TITLE
Feature Request: Run current cell hot key

### ISSUE THREAD

**Issue by quanvuong** [DonJayamanne/vscodeJupyter#35]

**Comment by gepcel** [comment]
If I'm not misunderstanding, there are two commands:

1. Jupyter: Run Cell
2. Jupyter: Run Cell and Advance

You can just bind them to your favorite shortcut key. Ignore if this isn't what you want.

**Comment by mosdeo** [comment]
Add those in keybindings.json, you can run cell as in Chrome

{ "key": "ctrl+enter", "command": "jupyter.execCurrentCell",
"when": "editorTextFocus"
}
