### ISSUE TITLE
Jupyter infinitely create "Python.exe" processes when working together with Python extension

### ISSUE THREAD

**Issue by dangoron** [DonJayamanne/vscodeJupyter#40]
### Environment data
VS Code version:1.11.2
Jupyter Extension version:1.1.1
OS and version:Windows 10 Pro 10.0.15063 
Anaconda version:4.3.1 (64-bit)
Python version:3.6.0
Jupyter version:4.2.1

### Logs
Output from ```Jupyter``` output panel
```
no output
```
Output from ```Console window``` (Help->Developer Tools menu)
```
no output
```

### Actual behavior
It infinitely creates "Python.exe" processes.
![](http://i1.piimg.com/567571/10e9fd4bf6312fdc.png)
### Expected  behavior
Show the result plots in ```Jupyter``` output panel.
### Steps to reproduce:
- Install "Python" extension and "Jupyter" extension
- Write the test python code, and click "Run cell", then booooom

**Comment by dangoron** [comment]
Well, I find the solution is actually using Python extension solely, without Jupyter.

**Comment by DonJayamanne** [comment]
What version of python are you using?  
What version of Jupyter are you using?  
Please upload contents of your user and workspace settings.json file.

**Comment by dangoron** [comment]
There were no settings related to python or jupyter in my user settings.json file. And I didn't use a workspace settings.json file. The content in user settings.json is shown as follows:
```js
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "Consolas, microsoft yahei",

    "files.associations": {
        "*.m": "matlab"
    },

    "editor.wordWrap": "on",

    // "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe",

    // Port number to use for connection.
    "remote.port": 52698,

    // Launch the server on start up.
    "remote.onstartup": true
}
```

**Comment by puma007** [comment]
When I click "run cell" link in vs code,it prompts “start a new notebook or select an existing notebook”. If i click the "start a new notebook" link,the Cpu occupancy rate will reach 99%, and start a lot of python threads!

**Comment by DonJayamanne** [comment]
@dangoron
What version of python are you using?
What version of Jupyter are you using?

**Comment by DonJayamanne** [comment]
@puma007
What version of python are you using?
What version of Jupyter are you using?

**Comment by puma007** [comment]
@DonJayamanne 
python version : 3.5
Jupyter vesion : 
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)

**Comment by dangoron** [comment]
@DonJayamanne 
Please see the environment data part in the first comment, I have already edited that :)

**Comment by zengjie** [comment]
@DonJayamanne 
Python version: 2.7.13
OS: macOS 10.12.4
Jupyter versions:
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
jupyter-kernel-gateway==0.5.0
jupyterlab==0.5.0

**Comment by DonJayamanne** [comment]
@dangoron @zengjie @puma007 
Hi everyone, please could you test the latest version. Hopefully this has been fixed.

**Comment by puma007** [comment]
@DonJayamanne when i click "run cell"link, and then select "start a new book",there is still error "Notebook not selected/started"

**Comment by DonJayamanne** [comment]
@puma007 what's the out put in the Jupyter out put panel in vscode? Also are there any other errors in the console log (help -> developer tools , console tab)

**Comment by puma007** [comment]
@DonJayamanne the console output the log:
`[Extension Host] vscode-icons is active!
messageService.ts:126 Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' commande.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] rejected promise not handled within 1 second
shell.ts:475 Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command`
