### ISSUE TITLE
Feature Request: Auto append "#%%" to the end of doc

### ISSUE THREAD

**Issue by liurui39660** [DonJayamanne/vscodeJupyter#42]
### Environment data
VS Code version: 1.11.2
Jupyter Extension version: 1.1.2
OS and version: Windows 10 Professional x64

My native language is not English, therefore to prevent misunderstanding, I leave no further message here, only my advice, sorry.

**Comment by DonJayamanne** [comment]
Sorry but I don't quite understand the requirement. Please provide an example.

**Comment by DonJayamanne** [comment]
Please provide more info and reopen
