### ISSUE TITLE
Advice - Continuous use of python console

### ISSUE THREAD

**Issue by emrahyigit** [DonJayamanne/vscodeJupyter#43]
For continuous use of python console, we can first initialize terminal with python.exe then execute the file using 'exec' command. Therefore, we can perform further operations on the results of the previously executed file. 

`const command = '${currentPythonPath}${launchArgsString}';` 
`if (utils_1.IS_WINDOWS) {` 
`const commandWin = command.replace(/\\/g, "/");`
`if (IS_POWERSHELL) {`
`terminal.sendText(`& ${commandWin}`);`
`        }`
`        else {`
`            terminal.sendText(commandWin);`
`        }`
`        const code = exec(open('${filePath}', 'rb').read());`
`        terminal.sendText(code.replace(/\\/g, "/"), true);`
`    }`

**Comment by DonJayamanne** [comment]
What's wrong with the current implementation? Wouldn't that work as well?

**Comment by emrahyigit** [comment]
Oh I am sorry, this question was for your Python tools for vscode, not for vsCodeJupyter;

When you click "Run Python File in Terminal", it runs the following command:

`python -B <filepath>`

But It executes and exits from python console and go back to cmd instantly.

**Comment by DonJayamanne** [comment]
Today you can send individual lines of text to the terminal using the Python extension.
