### ISSUE TITLE
Feature Request: Run selected text/line in terminal and move cursor to the expression

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/vscodeJupyter#44]
_From @AStupidBear on April 30, 2017 10:13_

I quite miss this feature in Jupyter.

_Copied from original issue: DonJayamanne/pythonVSCode#926_

**Comment by AStupidBear** [comment]
@DonJayamanne Is this difficult to implement? I see [julia-vscode](https://github.com/JuliaEditorSupport/julia-vscode/wiki/REPL) can run the current line and then move cursor to the next line/

**Comment by DonJayamanne** [comment]
Duplicate https://github.com/DonJayamanne/vscodeJupyter/issues/51
