### ISSUE TITLE
Feature request: Run Selection/Line and Advance

### ISSUE THREAD

**Issue by gepcel** [DonJayamanne/vscodeJupyter#51]
I can run the current cell and move cursor to the next cell by `Run Cell and Advance`.
But there seems no `Run Selection/Line and Advance` commnad there. It would be nice to be able to run the current line and move the cursor to the next line.

Update 2017-05-26 12:17:07: maybe duplication of issue #44 ?

**Comment by AStupidBear** [comment]
@gepcel I haven't see the command `Run Cell and Advance`. Where do you find that?

**Comment by gepcel** [comment]
I saw that from the command palette (via "Ctrl + Shift + P" under Windows system). As showing:
![image](https://cloud.githubusercontent.com/assets/4179106/26479904/21e82d62-4209-11e7-953d-ced7ae64cb0a.png)

And there's some information [here](https://github.com/DonJayamanne/vscodeJupyter/wiki/Jupyter:-Getting-Started#Miscellaneous-commands).

I thought of `Run Cell and Advance` as "Run the cell and move on". There is something similar in jupyter notebook like `Ctrl + Enter` and `Shift + Enter`. And also in "Hydrogen" of Atom:
![image](https://cloud.githubusercontent.com/assets/4179106/26480161/d16aa746-420a-11e7-8c57-81dd091dc418.png).

And what is more smarter in "Hydrogen" is that the `Run` command can detect either to run the current selection code or the code block where the cursor is in, more detail explained [here](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html#hydrogen-run). It will be much better if vscodeJupyter can accomplish this, too.

**Comment by AStupidBear** [comment]
@gepcel Thanks! I didn't see that command because I didn't add `#%%` before my code blocks.

**Comment by varun992** [comment]
Hi,

Any idea when would this be prioritized? It's becoming more of a necessity day by day! :(

**Comment by gepcel** [comment]
@varun992 You can use an extension called  "macros" to bind the two commands `jupyter.runSelectionLine` and `cursorDown` together and give it a new name and a shortcut.

So this feature is not needed anymore. I'll close this issue.

**Comment by varun992** [comment]
Thanks for that info, it works like a charm now.
