### ISSUE TITLE
404: Not found when run cell

### ISSUE THREAD

**Issue by tuanakka0101** [DonJayamanne/vscodeJupyter#55]
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.5
Python Version:   2.7.13
OS and version:    Ubuntu 17.04

## Actual behavior
When I run the example 
```
#%%
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np

x = np.linspace(0, 20, 100)
plt.plot(x, np.sin(x))
plt.show() 
```
by click Run cell. Output panel show error "404 : Not Found. You are requesting a page that does not exist!"
## Expected  behavior
As your demo, it will show a plot

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```    "python.jupyter.defaultKernel": "",
    "python.jupyter.startupCode": [
        "%matplotlib inline"
    ],
    "python.jupyter.appendResults": true, 
"python.pythonPath": "/usr/bin/python"
```   
## Logs
Output from ```Python``` output panel  
```
Starting Jupyter Notebook
jupyter notebook --no-browser --port=8888 --NotebookApp.allow_origin="*"
[W 13:45:48.009 NotebookApp] Widgets are unavailable. On Debian, notebook support for widgets is provided by the package jupyter-nbextension-jupyter-js-widgets
[I 13:45:48.023 NotebookApp] The port 8888 is already in use, trying another port.
[I 13:45:48.103 NotebookApp] Serving notebooks from local directory: /home/vnc/pyworkspace
[I 13:45:48.103 NotebookApp] 0 active kernels 
[I 13:45:48.104 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/
[I 13:45:48.104 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 13:45:49.153 NotebookApp] 404 GET /%20/api/kernelspecs?1497595548977 (127.0.0.1) 168.43ms referer=None
[W 13:47:34.123 NotebookApp] 404 GET /%20/api/kernelspecs?1497595654120 (127.0.0.1) 0.92ms referer=None
[W 13:50:20.664 NotebookApp] 404 GET /%20/api/kernelspecs?1497595820658 (127.0.0.1) 2.99ms referer=None
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by imsedim** [comment]
Could you please publish the updated extension? Looks like the latest version of extension 1.1.3 (May 2017) does not include this fix?

**Comment by eromoe** [comment]
Current version is unable to use, please update .

**Comment by imsedim** [comment]
As a workaround, I replayed the fix made in this issue (see [aa6df20](https://github.com/DonJayamanne/vscodeJupyter/commit/aa6df2045d12172fcafa0edd3c411ee1a8f469cb)) on my local machine:

Find the extension folder (on mac it's `~/.vscode/extensions/donjayamanne.jupyter-1.1.3`), find file `out/src/jupyterServices/notebook/utils.js` and replace line 
```
let parts = item.split('::').filter(part => part !== '::');
```
with
```
let parts = item.split('::').filter(part => part !== '::').map(part => part.trim());
```

That did the trick for me.

**Comment by eromoe** [comment]
@imsedim  Doesn't work for me. I tried disable and enable this plugin, but still same error . I have DonJayamanne/python plugin and DonJayamanne/jupyter plugin both installed. I see there are some code about jupyter in DonJayamanne/python . Does this affect ?

**Comment by imsedim** [comment]
@eromoe must be some other problem than. I mean, if you have nothing better to do with your time, you can try to download the source code and debug the extension (pretty simple thing to do).

As for the jupyter code in python - before vscodeJupyter extension existed, python extension used to support jupyter too. You can try to uninstall  vscodeJupyter altogether and try using python extension instead - but this didn't work for me honestly. 

PS: I have no relation to this repo. Just a fellow user.
