### ISSUE TITLE
Configuring python.jupyter.defaultKernel for Dockerized Jupyter

### ISSUE THREAD

**Issue by FuriouslyCurious** [DonJayamanne/vscodeJupyter#71]
### Environment data
VS Code version: Latest
Jupyter Extension version: Latest
OS and version: Mac OS X

Couldn't find the answer in Wiki so here goes: I have a jupyter kernel Dockerized, and I run it with following command:

> docker run -it --rm --ipc=host -p 8888:8888  Me/MyImage  jupyter notebook

How can I configure python.jupyter.defaultKernel to execute code using this kernel?

Thank you!

**Comment by DonJayamanne** [comment]
At the moment you can't. You could instead just add that as a task into your ```tasks.json``` and then use the command palette to specify the Jupyter remote url to connect to it.
