### ISSUE TITLE
Interactive debugging on remote kernel

### ISSUE THREAD

**Issue by csfoo** [DonJayamanne/vscodeJupyter#85]
Thanks for a great plugin!

I was trying to use the `%debug` magic command to interactively run ipdb on a remote kernel, but this does not seem to be supported at the moment as the UI hangs saying the kernel is busy. Am I missing something in how to get this to work?

**Comment by DonJayamanne** [comment]
Unfortunately the jupyter extension doesn't support debugging of kernels.
