### ISSUE TITLE
Can't start jupyter notebook with latest vscode jupyter and python extensions

### ISSUE THREAD

**Issue by breathe** [DonJayamanne/vscodeJupyter#90]
### Environment data
VS Code version: 1.18.1
Jupyter Extension version: 
OS and version:

### Logs
Output from ```Jupyter``` output panel
```
Starting Jupyter Notebook
jupyter notebook --no-browser --port=8888 --NotebookApp.allow_origin="*"
```
(It just hangs like this with 'Starting jupyter notebook text in vscode status panel)

Output from ```Console window``` (Help->Developer Tools menu)

<img width="1379" alt="screen shot 2017-11-27 at 9 15 48 am" src="https://user-images.githubusercontent.com/434034/33276738-9e039540-d353-11e7-9c8f-2a98196267ba.png">

### Actual behavior

Jupyter notebook fails to start

### Expected  behavior

Jupyter notebook starts

### Steps to reproduce:
- Open vscode
- run start jupyter notebook

The following config properties for jupyter/python are in effect ...

```
  "jupyter.notebook.startupFolder": "${workspaceFolder}/resources/FaqDataset",
  // "jupyter.appendResults": false,
  "jupyter.languages": [
    {
      "languageId": "python",
      "startupCode": []
    }
  ],
  "python.pythonPath": "${env.HOME}/anaconda3/envs/dev/bin/python",
  // TODO: change to ${env:HOME} paths so its portable across machines -- doesn't work yet tho
  // due to bug.  Bug was reported and fixed in master of pythonVSCode extension but new release
  // hasn't been cut yet.  Change these paths after the new release drops
  "python.linting.pylintPath": "${env.HOME}/anaconda3/envs/dev/bin/pylint",
  "python.linting.mypyPath": "${env.HOME}/anaconda3/envs/dev/bin/mypy",
  "python.linting.mypyEnabled": true,
  "python.linting.pylintArgs": ["--max-line-length=160"],
  "python.formatting.autopep8Args": ["--max-line-length", "160"]
```

Also fails if I change my workspace settings to following 

```
  "jupyter.notebook.startupFolder": "${workspaceFolder}/resources/FaqDataset",
  // "jupyter.appendResults": false,
  "jupyter.languages": [
    {
      "languageId": "python",
      "startupCode": []
    }
  ],
  "python.pythonPath": "/Users/bcohen/anaconda3/envs/dev/bin/python",
  // TODO: change to ${env:HOME} paths so its portable across machines -- doesn't work yet tho
  // due to bug.  Bug was reported and fixed in master of pythonVSCode extension but new release
  // hasn't been cut yet.  Change these paths after the new release drops
  "python.linting.pylintPath": "/Users/bcohen/anaconda3/envs/dev/bin/pylint",
  "python.linting.mypyPath": "/Users/bcohen/anaconda3/envs/dev/bin/mypy",
  "python.linting.mypyEnabled": true,
  "python.linting.pylintArgs": ["--max-line-length=160"],
  "python.formatting.autopep8Args": ["--max-line-length", "160"]
```

<img width="1379" alt="screen shot 2017-11-27 at 9 20 57 am" src="https://user-images.githubusercontent.com/434034/33276987-76c6b952-d354-11e7-9059-0d2391ac7c61.png">

**Comment by DonJayamanne** [comment]
This will be fixed in the next release of the Python extension (early-mid December).
Closing in favor of an upstream issue https://github.com/Microsoft/vscode-python/issues/245
